
/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class ImagePaths {
  static const String date = "assets/images/date.svg";
  static const String time = "assets/images/time.svg";
  static const String master = "assets/images/master.svg";
  static const String visa = "assets/images/visa.svg";
  static const String log = "assets/images/logo.svg";
  static const String group= "assets/images/group.svg";
  static const String warning= "assets/images/ic_warning.svg";
}
